feat: overlay images.
Financial-Times/origami-image-service pull request #848
Opened 2023-10-20 16:21 UTC by biggest-dave

Work in

2023-10-26 14:39 UTC, notlee requested changes
Looking good! One little bug and couple of suggestions here with our future maintenance in mind 🙏

2023-10-26 14:39 UTC, notlee commented on lib/transformers/cloudinary.js
> +		const overlayWidth = transform.getOverlayHeight();
Oops! Even when I found the problem, it took me so long to see that this was the cause 🙈 

```suggestion
		const overlayHeight = transform.getOverlayHeight();
		const overlayWidth = transform.getOverlayWidth();
```

2023-10-26 14:39 UTC, notlee commented on lib/image-transform.js
> +		this.overlay_width = value ? value : '';
Reviewing your PR is getting me more (re?) familiarised with the Image Service which is good 😄 Looks like `lib/image-transform.js` is intended as an abstraction layer. Should Cloudinary specific fallbacks be moved to `lib/transformers/cloudinary.js`?

2023-10-26 14:39 UTC, notlee commented on lib/image-transform.js
> +	 * @param {String} value
Could/should this be `{string|number}`?

2023-10-26 14:39 UTC, notlee commented on lib/image-transform.js
> +			this.setOverlayCrop(properties.overlay_crop);
For each of these, could we limit options here to a known set? Maybe even just the options you need right now? See `setGravity`. That way we have a smaller, more well defined task if we opt to move to a new supplier next year (but it's also quite easy to allow extra Cloudinary features).

2023-10-26 14:39 UTC, notlee commented on lib/image-transform.js
> +			return this.overlay;
Little indenting issue here (urgh, we need to set up a code formatter!)

2023-10-26 14:53 UTC, notlee commented
Also, bonus points! Apologies if I didn't think to mention before. Cache can be tricky with the image service. I suspect it would be a welcome ability to be able to "purge all images with x as their overlay" when we update an overlay's source image. To do that we'll want to set a [Surrogate Key](https://developer.fastly.com/reference/http/http-headers/Surrogate-Key/) on responses for Fastly.

I think that would happen as [part of the proxy response handler](https://github.com/Financial-Times/origami-image-service/blob/b1655858b90bf1455564f734431686030e5ef5e0/lib/image-service.js#L179). We'd want to differentiate an image used as an overlay vs. the same image being requested directly, so we'd maybe want to add something like `encodeKeys('overlay-' + overlayUrl)` conditionally, when an overlay is requested.

2023-10-26 15:34 UTC, biggest-dave commented on lib/transformers/cloudinary.js
> +		const overlayWidth = transform.getOverlayHeight();
Well spotted!

2023-10-30 15:58 UTC, biggest-dave commented on lib/image-transform.js
> +			this.setOverlayCrop(properties.overlay_crop);
I took out position and crop. I left gravity in as I could image that being used very soon (we're having debates about if it should come in from the south_east or south_west).

2023-10-30 16:09 UTC, notlee commented on lib/image-transform.js
> +			this.setOverlayCrop(properties.overlay_crop);
Then we can document the more limited set of values explicitly, rather than need people to reference Cloudinary docs.

2023-10-30 19:37 UTC, biggest-dave commented on lib/image-transform.js
> +			this.setOverlayCrop(properties.overlay_crop);
Done!

2023-10-31 09:04 UTC, notlee commented on lib/image-transform.js
> +			'thumb'
Can we reduce this list to just what you need for now? It'll make our potential transition to a new supplier easier

2023-10-31 11:37 UTC, biggest-dave commented on lib/image-transform.js
> +			'thumb'
done

2023-10-31 13:02 UTC, notlee approved these changes
Looks good! 🥳 🎉

2023-10-31 14:32 UTC, merged

2023-10-31 14:32 UTC, origamiserviceuser commented
:tada: This PR is included in version v453.10.0 :tada: